# Generated by Django 5.2.6 on 2025-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationfile',
            name='file',
            field=models.FileField(upload_to='consultation_files/'),
        ),
    ]
